@translate

Feature: Testing Google Translate


  Scenario Outline:
    Given open oxford dictionaries url
    And put the <word> to query box
    And press enter into query box
    And grab the real word
    Given open the url
    When select from english language
    Then select to bangla language
    And put the <word> to input box
    Then press translate button
    Then save the <word> result
    Given open synonyms url
    Then put the synonyms <word> to search box
    Then press submit button
    Then find relevancy list

    Examples:
    |word|
    |Withdraw|
    |withhold|
    |write|
    |win|
    |wear|
    |Tread|
    |Throw|
    |Tear|
    |take|
    |Swim|
    |Swear|
    |Strive|
    |Steal|
    |Stand|
    |Smite|
    |Slay|
    |shoot|
    |Shine|
    |shake|
    |Spin|
    |Spring|
    |Shrink|
    |Sink|
    |Sing|
    |see|
    |run|
    |Ring|
    |sea|
    |Ride|
    |meet|
    |Make|
    |know|
    |hide|
    |Grow|
    |go|
    |give|
    |Get|
    |Forsake|
    |Forget|
    |Forgive|
    |Forbid|
    |fly|
    |fight|
    |feed|
    |eat|
    |Drive|
    |Drink|
    |Draw|
    |do|
    |Dig|
    |Creep|
    |welcome|
    |come|
    |Cling|
    |Choose|
    |Chide|
    |Break|
    |hug|
    |Breed|
    |Bleed|
    |Bind|
    |Bid|
    |Beat|
    |behold|
    |Become|
    |be|
    |Arise|
    |Abide|
    |Weep|
    |Think|
    |Teach|
    |Sweep|
    |Spend|
    |Spell|
    |Smell|
    |Sleep|
    |send|
    |Seek|
    |Mean|
    |lose|
    |Lend|
    |Learn|
    |kneel|
    |keep|
    |feel|
    |Dwell|
    |deal|
    |Catch|
    |buy|
    |Burn|
    |build|
    |bend|
    |enjoy|
    |say|
    |Pay|
    |Lay|
    |marry|
    |hurry|
    |Try|
    |Fry|
    |Cry|
    |Carry|
    |bury|
    |Quarrel|
    |travel|
    |Refer|
    |Plan|
    |pat|
    |nod|
    |emit|
    |hop|
    |Drop|
    |cancel|
    |Beg|
    |tell|
    |Sell|
    |hear|
    |Have|
    |Move|
    |love|
    |Loose|
    |Lie|
    |live|
    |Hope|
    |Hate|
    |Gaze|
    |Divide|
    |Die|
    |dance|
    |Dare|
    |complete|
    |Compete|
    |Compare|
    |Change|
    |care|
    |Arrange|
    |Arrive|
    |Advise|
    |Agree|
    |Walk|
    |work|
    |wait|
    |Thank|
    |Stroke|
    |Stay|
    |show|
    |Sow|
    |Sew|
    |Rear|
    |Reach|
    |Rain|
    |punish|
    |push|
    |pull|
    |play|
    |pass|
    |Own|
    |Obey|
    |Need|
    |Mend|
    |look|
    |Lock|
    |load|
    |Laugh|
    |kill|
    |jump|
    |help|
    |hang|
    |Fill|
    |Fail|
    |Enjoy|
    |obliterate|
    |demolish|
    |shatter|
    |annihilate|
    |destroy|
    |undergo|
    |suffer|
    |dawn|
    |bask|
    |immerse|
    |stick|
    |dispose|
    |terminate|
    |be over|
    |finalize|
    |finish|
    |end|
    |conclude|
    |mast|
    |treasure|
    |utter delirium|
    |list|
    |hope|
    |suppose|
    |invent|
    |conceive|
    |imagine|
    |fancy|
    |Dream|
    |paint|
    |design|
    |intrigue|
    |consult|
    |argue|
    |deliberate|
    |discriminate|
    |smear|
    |prate|
    |speculate|
    |talk over|
    |reason|
    |handle|
    |examine|
    |speak|
    |have to do with|
    |Discuss|
    |frustrate|
    |hamper|
    |rein|
    |anticipate|
    |await|
    |tarry|
    |sidetrack|
    |shuffle off|
    |suspend|
    |prorogue|
    |defer|
    |cease|
    |adjourn|
    |loiter|
    |linger|
    |postpone|
    |hover|
    |Delay|
    |ascend|
    |rise|
    |mount|
    |attack|
    |ride|
    |Climb|
    |rectify|
    |sanctify|
    |decontaminate|
    |purify|
    |polish|
    |rub|
    |cleanse|
    |tidy up|
    |Clean|
    |Cheer|
    |resuscitate|
    |crew|
    |delight|
    |glorify|
    |commend|
    |compliment|
    |praise|
    |embolden|
    |exhort|
    |foster|
    |encourage|
    |cheer|
    |bear|
    |adopt|
    |copy|
    |echo|
    |imitate|
    |simulate|
    |emulate|
    |whet|
    |sharpen|
    |Borrow|
    |jug|
    |decoct|
    |accomplish|
    |seethe|
    |bloom|
    |Boil|
    |quest|
    |appeal|
    |wish|
    |implore|
    |solicit|
    |enquire|
    |interrogate|
    |question|
    |inquire|
    |Ask|
    |Telecast|
    |joggle|
    |infringe|
    |nudge|
    |pierce|
    |jostle|
    |jab|
    |press|
    |Thrust|
    |sputter|
    |Spit|
    |cage|
    |choke|
    |give over|
    |put an end|
    |close|
    |stop|
    |Shut|
    |maintain|
    |hold|
    |Set|
    |chronicle|
    |bless|
    |almighty|
    |indeed|
    |study|
    |fall|
    |read|
    |forsake|
    |throw over|
    |vacate|
    |omit|
    |outperform|
    |leave|
    |Quit|
    |lodge|
    |transit|
    |deposit|
    |quicken|
    |enforce|
    |shove|
    |place|
    |conduct|
    |consent|
    |approve|
    |accept|
    |let|
    |impinge|
    |backwash|
    |pip|
    |pang|
    |torture|
    |trouble|
    |penis|
    |prick|
    |gripe|
    |distress|
    |pain|
    |Hurt|
    |bid|
    |beat|
    |peeve|
    |strike|
    |bang|
    |knock|
    |blow|
    |shock|
    |rape|
    |rap|
    |hit|
    |separate|
    |interrupt|
    |mangle|
    |carve|
    |part|
    |sever|
    |split|
    |be divided|
    |obtruncate|
    |ax|
    |axe|
    |shear|
    |explode|
    |fulminate|
    |stake|
    |gage|
    |deploy|
    |propagate|
    |Band|
    |immigration|
    |undertake|
    |intended|
    |enroll|
    |proficiency|
    |sanction|
    |aver|
    |tear|
    |crucial|
    |beforehand|
    |Panic|
    |accent|
    |monotone|
    |Amazing|
    |conjugation|
    |cue|
    |Although|
    |usually|
    |devil|
    |offshore|
    |concerned|
    |emotion|
    |hypocrisy|
    |punctuality|
    |sincerity|
    |Introduce|
    |Pleased|
    |Indefinite|
    |lasts|
    |denote|
    |monster|
    |eternal|
    |habitual|
    |doer|
    |thought|
    |former|
    |Drill|
    |Dialogue|
    |Exemptions|
    |Articulation|
    |mastery|
    |capstone|
    |competent|
    |underpin|
    |Wisdom teeth|
    |Wisdom|
    |disclosing|
    |regression|
    |ensemble|
    |virtues|
    |ubiquitous|
    |density|
    |threshold|
    |epoch|
    |deferred|
    |Obligation|
    |through|
    |landmarks|
    |across|
    |greeting|
    |mention|
    |victim|
    |lifting|
    |constellations|
    |evil|
    |sword|
    |spell|
    |oppressor|
    |mansion|
    |valiant|
    |thrilling|
    |battle|
    |barely|
    |squirt|
    |groceries|
    |hold on|
    |orphans|
    |much|
    |earthquake|
    |naughty|
    |Shrimp|
    |fiery|
    |fear|
    |scream|
    |lyrics|
    |irritating|
    |depicts|
    |slap|
    |hair|
    |native|
    |demonstrate|
    |snacks|
    |Accommodation|
    |entrance|
    |devotees|
    |surrounding|
    |monastery|
    |contemporary|
    |sculpture|
    |gather|
    |site|
    |holy|
    |regarded|
    |hill|
    |pagoda|
    |outskirts|
    |Tasteless|
    |Courage|
    |Celebrity|
    |patience|
    |Long|
    |Hot|
    |Efficient|
    |Boring|
    |Asocial|
    |Worthy|
    |Reliable|
    |Executive|
    |Correspondent|
    |punctual|
    |Ambitious|
    |Certainly|
    |By the window|
    |Contemporary|
    |Affirmative|
    |Phonetics|
    |crying|
    |pleased|
    |won't|
    |will|
    |modal|
    |danger|
    |Shouldn't|
    |hardly|
    |live|
    |away|
    |flee|
    |peace|
    |wherever|
    |intervention|
    |rough|
    |acronym|
    |Transparency|
    |tolerance|
    |consistent|
    |knife|
    |candidate|
    |features|
    |emerge|
    |significant|
    |potential|
    |disappointing|
    |disappointed|
    |alike|
    |clustering|
    |existence|
    |accompanied|
    |crucial|
    |consolidates|
    |mining|
    |hype|
    |Naughty|
    |elegance|
    |veteran|
    |Transit|
    |Transitions|
    |ellipsis|
    |behave|
    |bet|
    |gadgets|
    |recognize|
    |dull|
    |yawn|
    |bandit|
    |rabbit|
    |contingency|
    |obtain|
    |predict|
    |prediction|
    |quake|
    |seismic|
    |prospectus|
    |prospect|
    |prospects|
    |mineral|
    |crops|
    |reject|
    |designated|
    |apart|
    |intrinsic|
    |traits|
    |discernible|
    |under the hood|
    |familiar|
    |compatibility|
    |Be Right Back (brb)|
    |equipped|
    |delegate|
    |nutshell|
    |ancestor|
    |Descendant|
    |whatsoever|
    |quickie|
    |rivals|
    |Artisan|
    |accumulator|
    |scratch|
    |Convener|
    |Mentor|
    |compatible|
    |backwards|
    |evolution|
    |complementary|
    |authorization|
    |authentication|
    |Bent|
    |grave|
    |organic|
    |accommodated|
    |anticipated|
    |emphasize|
    |norms|
    |Speculate|
    |envision|
    |grace|
    |Reduction|
    |Loyalty|
    |heuristic|
    |implication|
    |extensive|
    |reasoning|
    |perceive|
    |dignify|
    |identical|
    |axiom|
    |frontier|
    |tends|
    |beyond|
    |percept|
    |perceptual|
    |tract|
    |agent|
    |pedestrians|
    |trip|
    |perceiving|
    |extrapolate|
    |circumstances|
    |exhibited|
    |thin|
    |further|
    |furthermore|
    |wafers|
    |defects|
    |expectations|
    |Epics|
    |Sprint|
    |Sprints|
    |Backlog|
    |foggy|
    |Manifest|
    |encourages|
    |Pitfall|
    |Mining|
    |warehouse|
    |worst|
    |circuit|
    |malfunction|
    |iterate|
    |nuisance|
    |therefore|
    |explicitly|
    |accustomed|
    |adopted|
    |canonical|
    |through|
    |accomplished|
    |whether|
    |regardless|
    |exercise|
    |permissive|
    |spec|
    |hazardous|
    |naive|
    |affiliated|
    |Directives|
    |tactical|
    |held|
    |roughly|
    |tall|
    |wide|
    |precisely|
    |densities|
    |gesture|
    |Intent|
    |governs|
    |periodic|
    |spoof|
    |guess|
    |intercept|
    |interception|
    |Modification|
    |snoop|
    |withdraws|
    |withdraw|
    |malicious|
    |conceal|
    |confidentiality|
    |sake|
    |cipher|
    |exponents|
    |depressing|
    |wunder|
    |glimpse|
    |treat|
    |Intended|
    |grunt|
    |agile|
    |daemon|
    |Enhanced|
    |couple|
    |semantics|
    |merchant|
    |Canonical|
    |Transient|
    |consistent|
    |collaborate|
    |autonomous|
    |coherent|
    |written to be reviewed|
    |nowhere|
    |criticize|
    |junk|
    |scratch|
    |forces|
    |atmosphere|
    |terminologies|
    |assumption|
    |relate|
    |obvious|
    |Audience|
    |adapt|
    |rather than|
    |especially|
    |worthwhile|
    |Excerpt|
    |aside|
    |leave|
    |suddenly|
    |relatively|
    |intact|
    |implies|
    |ingredients|
    |depiction|
    |fork|
    |migration|
    |Sincerely|
    |compliance|
    |Restrict|
    |freak|
    |Disclosure|
    |compliances|
    |vague|
    |assurance|
    |deficient|
    |team spirit|
    |organizational culture|
    |Confidence|
    |personnel|
    |Competence|
    |identification|
    |performance|
    |integrity|
    |defined|
    |management|
    |like as|
    |such as|
    |criteria|
    |Skillful|
    |Effort|
    |Sincere|
    |Intention|
    |aspects|
    |emphasis|
    |approach|
    |involved|
    |factors|
    |Except|
    |preceding|
    |instead of|
    |Interacting|
    |treated|
    |rather|
    |desired|
    |meat|
    |survive|
    |verbose|
    |bias|
    |representation|
    |entry|
    |entire|
    |enforcement|
    |violate|
    |Representational|
    |Required|
    |tunnel|
    |bulky|
    |aggregates|
    |procedure|
    |borrow|
    |underlying|
    |foundation|
    |adequately|
    |beyond|
    |comprehensive|
    |complement|
    |Fetch|
    |Determine|
    |Derivation|
    |Surrounded|
    |Gathering|
    |Facilitate|
    |Transpose|
    |Adjacent|
    |Remaining|
    |Ancestor|
    |leaf|
    |Designation|
    |elementary|
    |Allow|
    |Containing|
    |Representation|
    |Intermediate|
    |Semantic|
    |Components|
    |pretend|
    |potentially|
    |negotiate|
    |Scrum|
    |spectrum|
    |versatile|
    |Intermediary|
    |wet|
    |remaining|
    |Discover|
    |Detection|
    |stringent|
    |Impose|
    |such|
    |held|
    |release|
    |voluntary|
    |bitch|
    |circular|
    |thus|
    |mutual|
    |sneaky|
    |unscrupulous|
    |corrupt|
    |principled|
    |obedient|
    |talented|
    |absent-minded|
    |coward|
    |cowardly|
    |brave|
    |modest|
    |conceited|
    |unfriendly|
    |friendly|
    |cheeky|
    |crude|
    |sophisticated|
    |impatient|
    |patient|
    |boring|
    |witty|
    |funny|
    |polite|
    |emotional|
    |impolite|
    |bad-mannered|
    |rude|
    |easy-going|
    |extroverted|
    |introverted|
    |shy|
    |adventurous|
    |caution|
    |outgoing|
    |stupid|
    |unhappy|
    |snobbish|
    |arrogant|
    |unintelligent|
    |intelligent|
    |clever|
    |lazy|
    |moody|
    |bad-tempered|
    |good-humoured|
    |dishonest|
    |honest|
    |sensible|
    |crazy|
    |mean|
    |kind|
    |generous|
    |cheerful|
    |impulsive|
    |hot-headed|
    |calm|
    |sensitive|
    |confident|
    |disgusted|
    |livid|
    |furious|
    |angry|
    |annoyed|
    |exhausted|
    |weary|
    |tired|
    |anxious|
    |stressed|
    |relaxed|
    |enthusiastic|
    |astonished|
    |surprised|
    |delighted|
    |fed up|
    |bored|
    |excited|
    |depressed|
    |worried|
    |miserable|
    |sad|
    |happy|
    |redhead|
    |brunette|
    |ginger-haired|
    |dark-haired|
    |brown-haired|
    |blonde|
    |blonde-haired|
    |fair-haired|
    |curly hair|
    |straight hair|
    |short hair|
    |long hair|
    |moustache|
    |beard|
    |scalp|
    |bald-headed|
    |bald|
    |middle-aged|
    |young|
    |old|
    |ugly|
    |handsome|
    |beautiful|
    |attractive|
    |scruffy|
    |smart|
    |well-dressed|
    |medium height|
    |overweight|
    |well-built|
    |fat|
    |slim|
    |short|
    |Describe People Start|
    |outfit|
    |phrase|
    |obese|
    |Enthusiastic|
    |typical|
    |nowadays|
    |intend|
    |Treat|
    |as well as|
    |day labor|
    |having|
    |orchards|
    |interest|
    |interesting|
    |castle|
    |rich|
    |facilities|
    |city|
    |town|
    |quit|
    |quiet|
    |verbose|
    |annoying|
    |exactly|
    |aka|
    |whatever|
    |literally|
    |rephrase|
    |arrivederci|
    |allergies|
    |definitely|
    |glory|
    |gracias|
    |i have to go|
    |guard|
    |idiot|
    |drop|
    |dropped|
    |reward|
    |that's that|
    |kittens|
    |betray|
    |brought|
    |dearly|
    |whisperer|
    |buddy|
    |one more time|
    |secret|
    |hideout|
    |giant|
    |straight|
    |grew|
    |vine|
    |learn|
    |gather|
    |gather around|
    |temper|
    |scrappy|
    |gonzalo|
    |perla|
    |led|
    |betrayed|
    |ones|
    |very|
    |mama|
    |pray|
    |reputation|
    |mine|
    |fish sticks|
    |freedom|
    |grant|
    |them|
    |diablo|
    |diablos|
    |guy|
    |these|
    |devils|
    |joke|
    |open|
    |nothing|
    |encountered|
    |ever|
    |mercenaries|
    |ferocious|
    |vile|
    |warn|
    |capture|
    |henchmen|
    |payment|
    |tears|
    |emphasis|
    |ridiculous|
    |identity|
    |distinguish|
    |together|
    |kingdom|
    |jewel|
    |crown|
    |ruby|
    |signore|
    |mercy|
    |majesty|
    |gato|
    |pretty|
    |anyway|
    |charged|
    |outrageous|
    |boots|
    |outlaw|
    |destined|
    |crossroads|
    |adventure|
    |goose|
    |lookup|
    |explanation|
    |identify|
    |cloudy|
    |becoming|
    |acidic|
    |certain|
    |lemon|
    |carefully|
    |understood|
    |footnote|
    |footnotes|
    |might|
    |venture|
    |patterns|
    |society|
    |mountainous|
    |experts|
    |different|
    |forward|
    |argument|
    |contained|
    |industry|
    |bar|
    |soap|
    |humble|
    |travelling|
    |through|
    |breakthrough|
    |recent|
    |outlines|
    |expand|
    |expanding|
    |trends|
    |water|
    |altitude|
    |climate|
    |impact|
    |assessing|
    |isolated|
    |connection|
    |virtual|
    |lake|
    |glacial|
    |alpine|
    |liquid|
    |temperature|
    |soluble|
    |their|
    |medicine|
    |galls|
    |oak|
    |alkaline|
    |remains|
    |clear|
    |dissolve|
    |associated|
    |bitter|
    |astringent|
    |responsible|
    |they|
    |chemicals|
    |plant|
    |tannins|
    |heard|
    |probably|
    |terrific|
    |awesome|
    |horrible|
    |wretched|
    |deserve|
    |deserved|
    |stuck|
    |instead|
    |supposed|
    |typographical|
    |mansion|
    |Squirt|
    |barely|
    |feature|
    |those|
    |According|
    |Withdraw|
    |withhold|
    |write|
    |win|
    |wear|
    |Tread|
    |Throw|
    |Tear|
    |take|
    |Swim|
    |Swear|
    |Strive|
    |Steal|
    |Stand|
    |Smite|
    |Slay|
    |shoot|
    |Shine|
    |shake|
    |Spin|
    |Spring|
    |Shrink|
    |Sink|
    |Sing|
    |see|
    |run|
    |Ring|
    |sea|
    |Ride|
    |meet|
    |Make|
    |know|
    |hide|
    |Grow|
    |go|
    |give|
    |Get|
    |Forsake|
    |Forget|
    |Forgive|
    |Forbid|
    |fly|
    |fight|
    |feed|
    |eat|
    |Drive|
    |Drink|
    |Draw|
    |do|
    |Dig|
    |Creep|
    |welcome|
    |come|
    |Cling|
    |Choose|
    |Chide|
    |Break|
    |hug|
    |Breed|
    |Bleed|
    |Bind|
    |Bid|
    |Beat|
    |behold|
    |Become|
    |be|
    |Arise|
    |Abide|
    |Weep|
    |Think|
    |Teach|
    |Sweep|
    |Spend|
    |Spell|
    |Smell|
    |Sleep|
    |send|
    |Seek|
    |Mean|
    |lose|
    |Lend|
    |Learn|
    |kneel|
    |keep|
    |feel|
    |Dwell|
    |deal|
    |Catch|
    |buy|
    |Burn|
    |build|
    |bend|
    |enjoy|
    |say|
    |Pay|
    |Lay|
    |marry|
    |hurry|
    |Try|
    |Fry|
    |Cry|
    |Carry|
    |bury|
    |Quarrel|
    |travel|
    |Refer|
    |Plan|
    |pat|
    |nod|
    |emit|
    |hop|
    |Drop|
    |cancel|
    |Beg|
    |tell|
    |Sell|
    |hear|
    |Have|
    |Move|
    |love|
    |Loose|
    |Lie|
    |live|
    |Hope|
    |Hate|
    |Gaze|
    |Divide|
    |Die|
    |dance|
    |Dare|
    |complete|
    |Compete|
    |Compare|
    |Change|
    |care|
    |Arrange|
    |Arrive|
    |Advise|
    |Agree|
    |Walk|
    |work|
    |wait|
    |Thank|
    |Stroke|
    |Stay|
    |show|
    |Sow|
    |Sew|
    |Rear|
    |Reach|
    |Rain|
    |punish|
    |push|
    |pull|
    |play|
    |pass|
    |Own|
    |Obey|
    |Need|
    |Mend|
    |look|
    |Lock|
    |load|
    |Laugh|
    |kill|
    |jump|
    |help|
    |hang|
    |Fill|
    |Fail|
    |Enjoy|
    |obliterate|
    |demolish|
    |shatter|
    |annihilate|
    |destroy|
    |undergo|
    |suffer|
    |dawn|
    |bask|
    |immerse|
    |stick|
    |dispose|
    |terminate|
    |be over|
    |finalize|
    |finish|
    |end|
    |conclude|
    |mast|
    |treasure|
    |utter delirium|
    |list|
    |hope|
    |suppose|
    |invent|
    |conceive|
    |imagine|
    |fancy|
    |Dream|
    |paint|
    |design|
    |intrigue|
    |consult|
    |argue|
    |deliberate|
    |discriminate|
    |smear|
    |prate|
    |speculate|
    |talk over|
    |reason|
    |handle|
    |examine|
    |speak|
    |have to do with|
    |Discuss|
    |frustrate|
    |hamper|
    |rein|
    |anticipate|
    |await|
    |tarry|
    |sidetrack|
    |shuffle off|
    |suspend|
    |prorogue|
    |defer|
    |cease|
    |adjourn|
    |loiter|
    |linger|
    |postpone|
    |hover|
    |Delay|
    |ascend|
    |rise|
    |mount|
    |attack|
    |ride|
    |Climb|
    |rectify|
    |sanctify|
    |decontaminate|
    |purify|
    |polish|
    |rub|
    |cleanse|
    |tidy up|
    |Clean|
    |Cheer|
    |resuscitate|
    |crew|
    |delight|
    |glorify|
    |commend|
    |compliment|
    |praise|
    |embolden|
    |exhort|
    |foster|
    |encourage|
    |cheer|
    |bear|
    |adopt|
    |copy|
    |echo|
    |imitate|
    |simulate|
    |emulate|
    |whet|
    |sharpen|
    |Borrow|
    |jug|
    |decoct|
    |accomplish|
    |seethe|
    |bloom|
    |Boil|
    |quest|
    |appeal|
    |wish|
    |implore|
    |solicit|
    |enquire|
    |interrogate|
    |question|
    |inquire|
    |Ask|
    |Telecast|
    |joggle|
    |infringe|
    |nudge|
    |pierce|
    |jostle|
    |jab|
    |press|
    |Thrust|
    |sputter|
    |Spit|
    |cage|
    |choke|
    |give over|
    |put an end|
    |close|
    |stop|
    |Shut|
    |maintain|
    |hold|
    |Set|
    |chronicle|
    |bless|
    |almighty|
    |indeed|
    |study|
    |fall|
    |read|
    |forsake|
    |throw over|
    |vacate|
    |omit|
    |outperform|
    |leave|
    |Quit|
    |lodge|
    |transit|
    |deposit|
    |quicken|
    |enforce|
    |shove|
    |place|
    |conduct|
    |consent|
    |approve|
    |accept|
    |let|
    |impinge|
    |backwash|
    |pip|
    |pang|
    |torture|
    |trouble|
    |penis|
    |prick|
    |gripe|
    |distress|
    |pain|
    |Hurt|
    |bid|
    |beat|
    |peeve|
    |strike|
    |bang|
    |knock|
    |blow|
    |shock|
    |rape|
    |rap|
    |hit|
    |separate|
    |interrupt|
    |mangle|
    |carve|
    |part|
    |sever|
    |split|
    |be divided|
    |obtruncate|
    |ax|
    |axe|
    |shear|
    |explode|
    |fulminate|
    |stake|
    |gage|
    |deploy|
    |propagate|
    |Band|
    |immigration|
    |undertake|
    |intended|
    |enroll|
    |proficiency|
    |sanction|
    |aver|
    |tear|
    |crucial|
    |beforehand|
    |Panic|
    |accent|
    |monotone|
    |Amazing|
    |conjugation|
    |cue|
    |Although|
    |usually|
    |devil|
    |offshore|
    |concerned|
    |emotion|
    |hypocrisy|
    |punctuality|
    |sincerity|
    |Introduce|
    |Pleased|
    |Indefinite|
    |lasts|
    |denote|
    |monster|
    |eternal|
    |habitual|
    |doer|
    |thought|
    |former|
    |Drill|
    |Dialogue|
    |Exemptions|
    |Articulation|
    |mastery|
    |capstone|
    |competent|
    |underpin|
    |Wisdom teeth|
    |Wisdom|
    |disclosing|
    |regression|
    |ensemble|
    |virtues|
    |ubiquitous|
    |density|
    |threshold|
    |epoch|
    |deferred|
    |Obligation|
    |through|
    |landmarks|
    |across|
    |greeting|
    |mention|
    |victim|
    |lifting|
    |constellations|
    |evil|
    |sword|
    |spell|
    |oppressor|
    |mansion|
    |valiant|
    |thrilling|
    |battle|
    |squirt|
    |groceries|
    |hold on|
    |orphans|
    |much|
    |earthquake|
    |naughty|
    |Shrimp|
    |fiery|
    |fear|
    |scream|
    |lyrics|
    |irritating|
    |depicts|
    |slap|
    |hair|
    |native|
    |demonstrate|
    |snacks|
    |Accommodation|
    |entrance|
    |devotees|
    |surrounding|
    |monastery|
    |contemporary|
    |sculpture|
    |gather|
    |site|
    |holy|
    |regarded|
    |hill|
    |pagoda|
    |outskirts|
    |Tasteless|
    |Courage|
    |Celebrity|
    |patience|
    |Long|
    |Hot|
    |Efficient|
    |Boring|
    |Asocial|
    |Worthy|
    |Reliable|
    |Executive|
    |Correspondent|
    |punctual|
    |Ambitious|
    |Certainly|
    |By the window|
    |Contemporary|
    |Affirmative|
    |Phonetics|
    |crying|
    |pleased|
    |won't|
    |will|
    |modal|
    |danger|
    |Shouldn't|
    |hardly|
    |live|
    |away|
    |flee|
    |peace|
    |wherever|
    |intervention|
    |rough|
    |acronym|
    |Transparency|
    |tolerance|
    |consistent|
    |knife|
    |candidate|
    |features|
    |emerge|
    |significant|
    |potential|
    |disappointing|
    |disappointed|
    |alike|
    |clustering|
    |existence|
    |accompanied|
    |crucial|
    |consolidates|
    |mining|
    |hype|
    |Naughty|
    |elegance|
    |veteran|
    |Transit|
    |Transitions|
    |ellipsis|
    |behave|
    |bet|
    |gadgets|
    |recognize|
    |dull|
    |yawn|
    |bandit|
    |rabbit|
    |contingency|
    |obtain|
    |predict|
    |prediction|
    |quake|
    |seismic|
    |prospectus|
    |prospect|
    |prospects|
    |mineral|
    |crops|
    |reject|
    |designated|
    |apart|
    |intrinsic|
    |traits|
    |discernible|
    |under the hood|
    |familiar|
    |compatibility|
    |Be Right Back (brb)|
    |equipped|
    |delegate|
    |nutshell|
    |ancestor|
    |Descendant|
    |whatsoever|
    |quickie|
    |rivals|
    |Artisan|
    |accumulator|
    |scratch|
    |Convener|
    |Mentor|
    |compatible|
    |backwards|
    |evolution|
    |complementary|
    |authorization|
    |authentication|
    |Bent|
    |grave|
    |organic|
    |accommodated|
    |anticipated|
    |emphasize|
    |norms|
    |Speculate|
    |envision|
    |grace|
    |Reduction|
    |Loyalty|
    |heuristic|
    |implication|
    |extensive|
    |reasoning|
    |perceive|
    |dignify|
    |identical|
    |axiom|
    |frontier|
    |tends|
    |beyond|
    |percept|
    |perceptual|
    |tract|
    |agent|
    |pedestrians|
    |trip|
    |perceiving|
    |extrapolate|
    |circumstances|
    |exhibited|
    |thin|
    |further|
    |furthermore|
    |wafers|
    |defects|
    |expectations|
    |Epics|
    |Sprint|
    |Sprints|
    |Backlog|
    |foggy|
    |Manifest|
    |encourages|
    |Pitfall|
    |Mining|
    |warehouse|
    |worst|
    |circuit|
    |malfunction|
    |iterate|
    |nuisance|
    |therefore|
    |explicitly|
    |accustomed|
    |adopted|
    |canonical|
    |accomplished|
    |whether|
    |regardless|
    |exercise|
    |permissive|
    |spec|
    |hazardous|
    |naive|
    |affiliated|
    |Directives|
    |tactical|
    |held|
    |roughly|
    |tall|
    |wide|
    |precisely|
    |densities|
    |gesture|
    |Intent|
    |governs|
    |periodic|
    |spoof|
    |guess|
    |intercept|
    |interception|
    |Modification|
    |snoop|
    |withdraws|
    |withdraw|
    |malicious|
    |conceal|
    |confidentiality|
    |sake|
    |cipher|
    |exponents|
    |depressing|
    |wunder|
    |glimpse|
    |treat|
    |Intended|
    |grunt|
    |agile|
    |daemon|
    |Enhanced|
    |couple|
    |semantics|
    |merchant|
    |Canonical|
    |Transient|
    |consistent|
    |collaborate|
    |autonomous|
    |coherent|
    |written to be reviewed|
    |nowhere|
    |criticize|
    |junk|
    |scratch|
    |forces|
    |atmosphere|
    |terminologies|
    |assumption|
    |relate|
    |obvious|
    |Audience|
    |adapt|
    |rather than|
    |especially|
    |worthwhile|
    |Excerpt|
    |aside|
    |leave|
    |suddenly|
    |relatively|
    |intact|
    |implies|
    |ingredients|
    |depiction|
    |fork|
    |migration|
    |Sincerely|
    |compliance|
    |Restrict|
    |freak|
    |Disclosure|
    |compliances|
    |vague|
    |assurance|
    |deficient|
    |team spirit|
    |organizational culture|
    |Confidence|
    |personnel|
    |Competence|
    |identification|
    |performance|
    |integrity|
    |defined|
    |management|
    |like as|
    |such as|
    |criteria|
    |Skillful|
    |Effort|
    |Sincere|
    |Intention|
    |aspects|
    |emphasis|
    |approach|
    |involved|
    |factors|
    |Except|
    |preceding|
    |instead of|
    |Interacting|
    |treated|
    |rather|
    |desired|
    |meat|
    |survive|
    |verbose|
    |bias|
    |representation|
    |entry|
    |entire|
    |enforcement|
    |violate|
    |Representational|
    |Required|
    |tunnel|
    |bulky|
    |aggregates|
    |procedure|
    |borrow|
    |underlying|
    |foundation|
    |adequately|
    |beyond|
    |comprehensive|
    |complement|
    |Fetch|
    |Determine|
    |Derivation|
    |Surrounded|
    |Gathering|
    |Facilitate|
    |Transpose|
    |Adjacent|
    |Remaining|
    |Ancestor|
    |leaf|
    |Designation|
    |elementary|
    |Allow|
    |Containing|
    |Representation|
    |Intermediate|
    |Semantic|
    |Components|
    |pretend|
    |potentially|
    |negotiate|
    |Scrum|
    |spectrum|
    |versatile|
    |Intermediary|
    |wet|
    |remaining|
    |Discover|
    |Detection|
    |stringent|
    |Impose|
    |such|
    |held|
    |release|
    |voluntary|
    |bitch|
    |circular|
    |thus|
    |mutual|
    |sneaky|